problem = "matrix-completion" 
gt_path = "datasets/mat-exp3/test_CAM_300_Out_0.4_miss_0.4_gt.pt" 
shape = [900, 900] 
obs_path = "datasets/mat-exp3/test_CAM_300_Out_0.4_miss_0.4_obs.pt" 
dataset = "test_CAM_300_Out_0.4_miss_0.4" 
unobs_path = "datasets/mat-exp3/test_CAM_300_Out_0.4_miss_0.4_unobs.pt" 
fraction_missing = 0.4 
outlier_probabilty = 0.4 
cameras = 300 
