problem = "matrix-completion" 
gt_path = "datasets/mat-exp3/test_CAM_300_Out_0.3_miss_0.5_gt.pt" 
shape = [900, 900] 
obs_path = "datasets/mat-exp3/test_CAM_300_Out_0.3_miss_0.5_obs.pt" 
dataset = "test_CAM_300_Out_0.3_miss_0.5" 
unobs_path = "datasets/mat-exp3/test_CAM_300_Out_0.3_miss_0.5_unobs.pt" 
fraction_missing = 0.5 
outlier_probabilty = 0.3 
cameras = 300 
