problem = "matrix-completion" 
gt_path = "datasets/mat-exp3/test_CAM_300_Out_0.3_miss_0.9_gt.pt" 
shape = [900, 900] 
obs_path = "datasets/mat-exp3/test_CAM_300_Out_0.3_miss_0.9_obs.pt" 
dataset = "test_CAM_300_Out_0.3_miss_0.9" 
unobs_path = "datasets/mat-exp3/test_CAM_300_Out_0.3_miss_0.9_unobs.pt" 
fraction_missing = 0.9 
outlier_probabilty = 0.3 
cameras = 300 
