problem = "matrix-completion" 
gt_path = "datasets/mat-exp3/test_CAM_300_Out_0.2_miss_0.8_gt.pt" 
shape = [900, 900] 
obs_path = "datasets/mat-exp3/test_CAM_300_Out_0.2_miss_0.8_obs.pt" 
dataset = "test_CAM_300_Out_0.2_miss_0.8" 
unobs_path = "datasets/mat-exp3/test_CAM_300_Out_0.2_miss_0.8_unobs.pt" 
fraction_missing = 0.8 
outlier_probabilty = 0.2 
cameras = 300 
